[package]
name = "plutus-parser-derive"
version = "0.2.0"
edition = "2024"
description = "Macro implementation of #[derive(AsPlutus)]"
license = "Apache-2.0"
repository = "https://github.com/SundaeSwap-finance/plutus-parser/"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "2.0"
quote = "1.0"
